name: scouter
description: A NestJS inspired HTTP wrapper, to handle apis development following its code style
version: 1.1.1
repository: https://github.com/viniciusamelio/scouter
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  alfred: ^1.0.0+1
  fpdart: ^0.2.0
  kiwi: ^4.0.2

dev_dependencies:
  faker: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
